#pragma once

typedef enum ErrorCode {
	NO_ERROR,
	INIT_MPI_ERROR,
	FILE_OPEN_ERROR,
	FILE_CLOSE_ERROR,
	FILE_READ_ERROR,
	MEMORY_ALLOC_ERROR,
	MEMORY_FREE_ERROR,
	GET_FILE_SIZE_ERROR,
	GET_PROC_NAME_ERROR,
	GET_RANK_ERROR,
	GET_SIZE_ERROR
} ErrorCode;